#!/usr/bin/env python
'''
    This tool plots the gene counts for a set of organisms, where 
    the gene counts are calculated from a set of UniProtKB/SwissProt 
    files. One can run the program as follows: 

      >python plot_geneCounts -I1=sp_list.txt -I2=sprot_files.txt -I3=sprot_genes.stat.1

    The program will use the gene counts from sprot_genes.stat.1 file and draw 
    one graph for each organism. The description of the input file names:  
        sp_list.txt needs to have the list of species: column 1 has the 
            taxon ids and column 2 has the taxon name. 

        sprot_files.txt needs to have the SwissProt filenames. The 
            program extracts the time points from this file. Also, 
            each entry in this file corresponds to the rows in 
            sprot_genes.stat.1 file.

        sprot_genes.stat.1 needs to have the geen counts. 
            Each row corresponds to the SwissProt file name listed
            in sprot_files.txt file. For each organism, there are 
            there consecutive columns (for BPO, CCO, and MFO, 
            respectively). The columns corresponds to the species 
            listed in the sp_list.txt file.  
'''
import os
import sys
from os.path import basename 
from collections import defaultdict

import ArgParser_plot as ap
import Config
import ConfigParser as cp
import FormatChecker as fc
import LocateDataset as ld

import matplotlib.pyplot as plt

# Default configuration file name:
config_filename = '.config'
no_of_organisms = 10 

class plot_geneCounts:
    def __init__(self):
        # Collect user arguments into a dictionary:
        self.parsed_dict = ap.parse_args() 
        # Collect config file entries:
        self.ConfigParam = Config.read_config(config_filename)
        self.work_dir = self.ConfigParam['workdir']
        self.figure_dir = './figures'
        # Look for workspace, and if none exists create one:
        if not os.path.exists(self.work_dir):
            os.makedirs(self.work_dir) # Create work space

        # Extract species list file name: 
        t1 = self.parsed_dict['t1'] 
        # Locate file for the species list file:
        self.species_filename = ld.locate_anyfile(t1, self.work_dir)

        # Extract filename containing the list of SwissProt file names:
        t2 = self.parsed_dict['t2'] 
        # Locate the file containing the list of the UniProtKB/SwissProt
        # file names over a series of time points:
        self.sprot_fnList_filename = ld.locate_anyfile(t2, self.work_dir)

        # Extract the filename containing the gene counts:  
        t3 = self.parsed_dict['t3'] 
        # Locate the gene count file:
        self.geneCount_filename = ld.locate_anyfile(t3, self.work_dir)
        return None

    def create_fig_name(self, fname_prefix):
        """ 
        Creates an output filename based on the filename prefix
        provided by fname_prefix and at the end returns the newly
        created filename for a figure.
        Note:  
        The program uses index variable to find whether the previous
        versions (starting from one consecutively) of the file exists. 
        It returns the file name with the subsequent version. 
        """
        ob = fname_prefix
        index = 1
        while os.path.exists(self.figure_dir + '/' + ob + '.' + str(index) + '.png'):
            index = index + 1
        output_filename = self.figure_dir + '/' + ob + '.' + str(index) + '.png'
        return output_filename

    def convert_str2num_list(self, bpo_list, cco_list, mfo_list):
        for i in range(len(bpo_list)):
            bpo_list[i] = int(bpo_list[i])
            cco_list[i] = int(cco_list[i])
            mfo_list[i] = int(mfo_list[i])
        return (bpo_list, cco_list, mfo_list)

    def plot_and_save(self, bpo_list, cco_list, mfo_list, taxon_id, taxon_name):
        # Extract the time point list from the sprot file name list: 
        tp_lst = self.extract_timepoint_info(
                       open(self.sprot_fnList_filename, 'r'))
        #fig = plt.figure()
        fig = plt.figure(figsize=(10,10) )
        x_axis = range(1,11)
        #plt.subplot(3,1,1)
        ax_1=fig.add_subplot(3,1,1)
        plt_title = '# of Genes Annotated with Exp Evidence Codes:\n' + str(taxon_name) 
        plt.title(plt_title)
        plt.plot(x_axis, bpo_list, 'ro', x_axis, bpo_list, 'k')
        plt.ylabel('Gene Count')
        # Set offset to space at the top and bottom of the graph: 
        offset = (max(bpo_list) - min(bpo_list))/5
        plt.axis([0, 11, min(bpo_list) - offset, max(bpo_list) + offset])

        plt.xticks(x_axis, tp_lst, size='small', horizontalalignment='center')
        #plt.xticks(x_axis, tp_lst, horizontalalignment='center')
        text_ht = max(bpo_list) - (max(bpo_list)-min(bpo_list))/15
        ax_1.text(0.2, text_ht, 'BPO', fontsize=15)

        #plt.subplot(3,1,2)
        ax_2=fig.add_subplot(3,1,2)
        plt.plot(x_axis, cco_list, 'ro', x_axis, cco_list, 'k')
        plt.ylabel('Gene Count')
        offset = (max(cco_list) - min(cco_list))/5
        # Set offset to space at the top and bottom of the graph: 
        plt.axis([0, 11, min(cco_list)-offset, max(cco_list)+offset])

        plt.xticks(x_axis, tp_lst, size='small', horizontalalignment='center')
        #plt.xticks(x_axis, tp_lst, size='small', horizontalalignment='center')
        text_ht = max(cco_list) - (max(cco_list)-min(cco_list))/15
        ax_2.text(0.2, text_ht, 'CCO', fontsize=15)

        #plt.subplot(3,1,3) 
        ax_3=fig.add_subplot(3,1,3) 
        plt.plot(x_axis, mfo_list, 'ro', x_axis, mfo_list, 'k')
        plt.ylabel('Gene Count')
        # Set offset to space at the top and bottom of the graph: 
        offset = (max(mfo_list) - min(mfo_list))/5
        plt.axis([0, 11, min(mfo_list)-offset, max(mfo_list)+offset])

        plt.xticks(x_axis, tp_lst, size='small', horizontalalignment='center')
        #plt.xticks(x_axis, tp_lst, horizontalalignment='center')
        text_ht = max(mfo_list) - (max(mfo_list)-min(mfo_list))/15
        ax_3.text(0.2, text_ht, 'MFO', fontsize=15)

        # Get a file name for the figure to be saved: 
        fig_fname = self.create_fig_name('geneFreq.' + str(taxon_id))
        print fig_fname
        fig.savefig(fig_fname)
        #plt.show()

    def extract_taxon_info(self, fh): 
        taxon_id_list = []
        taxon_name_list = []
        for line in fh:
            taxon_id_list.append(line.strip().split('\t')[0])
            taxon_name_list.append(line.strip().split('\t')[1])
        return (taxon_id_list, taxon_name_list) 

    def extract_timepoint_info(self, fh): 
        tp_list = []
        for line in fh:
            tp_list.append(line.strip().split('.dat.')[-1])
        return tp_list 

    def extract_gene_count(self, tax_id_lst, fh): 
        # Initialize dictionary for gene count in BPO ontological group: 
        gc_bpo_dict = defaultdict(list) 
        # Initialize dictionary for gene count in CCO ontological group: 
        gc_cco_dict = defaultdict(list) 
        # Initialize dictionary for gene count in MFO ontological group: 
        gc_mfo_dict = defaultdict(list) 

        for line in fh:
            line_values = line.strip().split('\t')
            tp = line_values[0]
            id_no = 0
            for i in range(1,no_of_organisms*3+1,3):
                gc_bpo_dict[tax_id_lst[id_no]].append(line_values[i])
                gc_cco_dict[tax_id_lst[id_no]].append(line_values[i+1])
                gc_mfo_dict[tax_id_lst[id_no]].append(line_values[i+2])
                id_no += 1
        return (gc_bpo_dict, gc_cco_dict, gc_mfo_dict)

    def process_data(self): 
        # Extract taxon id list and taxon name list:
        tax_id_lst, tax_name_lst = self.extract_taxon_info(
                                        open(self.species_filename, 'r'))

         # Extract gene count from the gene count file:
        gc_bpo_dict, gc_cco_dict, gc_mfo_dict = self.extract_gene_count(
                                                     tax_id_lst, 
                                                     open(self.geneCount_filename, 'r'))

        # Extract gene counts for each organism, plot and save graphs:
        for i in range(0, len(tax_id_lst)):
            # Convert the gene counts from a list of 
            # strings to a list of numbers: 
            bpo_list, cco_list, mfo_list = self.convert_str2num_list(
                                                gc_bpo_dict[tax_id_lst[i]], 
                                                gc_cco_dict[tax_id_lst[i]],
                                                gc_mfo_dict[tax_id_lst[i]])
            # Plot the gene counts in BPO, CCO, and MFO ontological categories
            # and save the graph to a file:
            self.plot_and_save(bpo_list, 
                               cco_list, 
                               mfo_list, 
                               tax_id_lst[i], 
                               tax_name_lst[i])
#            break
        return None
if __name__ == '__main__':
    if len(sys.argv) == 1:
        print (sys.argv[0] + ':')
        print(__doc__)
    else:
        pg = plot_geneCounts() # Create an instance of plot_geneCount class
        pg.process_data()      # Process data
    sys.exit(0)


